@startuml
skinparam sequenceMessageAlign center
skinparam participantFontSize 12
skinparam sequenceParticipantFontSize 14
title Sequence Diagram for Java Program Flow

actor User as user
participant SatbifyController as app
participant Chords as chords
participant ChordConnector as connector


user -> app
app -> chords: harmonise()
chords -> chords:

@enduml
